import { useEffect, useMemo, useState } from "react";
import type { CanonEntityDetail, CanonSection, VisualLocksValue, SubBeatsValue } from "@cinematic/domain";
import { parseCanonSectionValue } from "@cinematic/domain";
import { describeError } from "../../lib/errors";
import { getCanonEntity, lockCanonSection, unlockCanonSection, upsertCanonSection } from "./api";
import { CanonSectionCard } from "./CanonSectionCard";
import { CanonHistoryDialog } from "./CanonHistoryDialog";

const textSections: Array<[string, string]> = [["role_tag", "Role Tag"], ["visual_summary", "Visual Summary"], ["function", "Function"], ["backstory", "Backstory"], ["psychology", "Psychology"], ["speech", "Speech"], ["movement", "Movement"], ["stillness", "Stillness"]];
const defaults: Record<string, unknown> = { role_tag: { text: "" }, visual_summary: { text: "" }, function: { text: "" }, backstory: { text: "" }, psychology: { text: "" }, speech: { text: "" }, movement: { text: "" }, stillness: { text: "" }, visual_locks: { locks: [] }, sub_beats: { beats: [] } };

export function CharacterEditor({ projectRootPath, entityId }: { projectRootPath: string; entityId: string }) {
  const [detail, setDetail] = useState<CanonEntityDetail | null>(null); const [error, setError] = useState<string | null>(null); const [history, setHistory] = useState<{ id: string; title: string } | null>(null);
  async function load() { try { setDetail(await getCanonEntity(projectRootPath, entityId)); setError(null); } catch (caught) { setError(describeError(caught)); } }
  useEffect(() => { void load(); }, [projectRootPath, entityId]);
  const sections = useMemo(() => new Map((detail?.sections ?? []).map((section) => [section.key, section])), [detail]);
  if (!detail) return <div className="canon-editor-pane">{error ? <p role="alert">{error}</p> : <p>Loading character…</p>}</div>;
  async function save(key: string, value: unknown) { await upsertCanonSection({ projectRootPath, entityId, sectionKey: key, value }); await load(); }
  async function mutateLock(section: CanonSection<unknown>, lock: boolean) { await (lock ? lockCanonSection : unlockCanonSection)({ projectRootPath, sectionId: section.id }); await load(); }
  return <div className="canon-editor-pane"><h3>{detail.entity.name}</h3>{error ? <p role="alert">{error}</p> : null}<div className="canon-section-grid">{[...textSections, ["visual_locks", "Visual Locks"], ["sub_beats", "Sub-beats"]].map(([key, title]) => { const section = sections.get(key) as CanonSection<unknown> | undefined; return <CharacterSection key={`${key}-${section?.revision ?? 0}-${section?.status ?? "draft"}`} title={title} sectionKey={key} section={section ?? null} value={section?.value ?? defaults[key]} onSave={save} onLock={mutateLock} onHistory={(id) => setHistory({ id, title })} />; })}</div><CanonHistoryDialog projectRootPath={projectRootPath} sectionId={history?.id ?? null} sectionTitle={history?.title ?? "Section"} onClose={() => setHistory(null)} /></div>;
}

function CharacterSection({ title, sectionKey, section, value, onSave, onLock, onHistory }: { title: string; sectionKey: string; section: CanonSection<unknown> | null; value: unknown; onSave: (key: string, value: unknown) => Promise<void>; onLock: (section: CanonSection<unknown>, lock: boolean) => Promise<void>; onHistory: (id: string) => void }) {
  const isText = textSections.some(([key]) => key === sectionKey);
  return <CanonSectionCard title={title} section={section} draftValue={value} validate={(input) => parseCanonSectionValue("character", sectionKey, input)} renderEditor={(draft, setDraft) => isText ? <textarea value={(draft as { text: string }).text} onChange={(event) => setDraft({ text: event.target.value })} rows={4} /> : <CharacterStructuredEditor sectionKey={sectionKey} value={draft} onChange={setDraft} />} renderReadOnly={(current) => isText ? <p>{(current as { text: string }).text ? `"${(current as { text: string }).text}"` : "[TBD]"}</p> : <CharacterStructuredReadOnly sectionKey={sectionKey} value={current} />} onSave={(next) => onSave(sectionKey, next)} onLock={() => section ? onLock(section, true) : Promise.resolve()} onUnlock={() => section ? onLock(section, false) : Promise.resolve()} onHistory={() => section && onHistory(section.id)} />;
}

function CharacterStructuredEditor({ sectionKey, value, onChange }: { sectionKey: string; value: unknown; onChange: (value: unknown) => void }) {
  if (sectionKey === "visual_locks") { const current = value as VisualLocksValue; return <div className="canon-list-editor">{current.locks.map((lock, index) => <div className="canon-list-row" key={lock.id}><label>Key<input value={lock.key} onChange={(event) => { const locks = [...current.locks]; locks[index] = { ...lock, key: event.target.value }; onChange({ locks }); }} /></label><label>Description<input value={lock.description} onChange={(event) => { const locks = [...current.locks]; locks[index] = { ...lock, description: event.target.value }; onChange({ locks }); }} /></label><label>Severity<select value={lock.severity} onChange={(event) => { const locks = [...current.locks]; locks[index] = { ...lock, severity: event.target.value as "required" | "important" }; onChange({ locks }); }}><option value="required">required</option><option value="important">important</option></select></label><label>Validator hint<input value={lock.validatorHint ?? ""} onChange={(event) => { const locks = [...current.locks]; locks[index] = { ...lock, validatorHint: event.target.value || null }; onChange({ locks }); }} /></label><button type="button" className="canon-secondary-button" onClick={() => onChange({ locks: current.locks.filter((_, rowIndex) => rowIndex !== index) })}>Remove</button></div>)}<button type="button" className="canon-secondary-button" onClick={() => onChange({ locks: [...current.locks, { id: crypto.randomUUID(), key: "", description: "", severity: "required", validatorHint: null }] })}>Add visual lock</button></div>; }
  const current = value as SubBeatsValue; return <div className="canon-list-editor">{current.beats.map((beat, index) => <div className="canon-list-row" key={beat.id}><label>Title<input value={beat.title} onChange={(event) => { const beats = [...current.beats]; beats[index] = { ...beat, title: event.target.value }; onChange({ beats }); }} /></label><label>Text<textarea value={beat.text} onChange={(event) => { const beats = [...current.beats]; beats[index] = { ...beat, text: event.target.value }; onChange({ beats }); }} /></label><button type="button" className="canon-secondary-button" onClick={() => onChange({ beats: current.beats.filter((_, rowIndex) => rowIndex !== index) })}>Remove</button></div>)}<button type="button" className="canon-secondary-button" onClick={() => onChange({ beats: [...current.beats, { id: crypto.randomUUID(), title: "", text: "" }] })}>Add sub-beat</button></div>;
}

function CharacterStructuredReadOnly({ sectionKey, value }: { sectionKey: string; value: unknown }) { if (sectionKey === "visual_locks") return <ul>{(value as VisualLocksValue).locks.map((lock) => <li key={lock.id}>[{lock.severity.toUpperCase()}] {lock.key} — {lock.description}</li>)}</ul>; return <ul>{(value as SubBeatsValue).beats.map((beat) => <li key={beat.id}><strong>{beat.title}</strong> — {beat.text}</li>)}</ul>; }
