import { useEffect, useMemo, useState } from "react";
import type { CanonEntity, CanonEntityDetail, CanonEntityType, CanonSection } from "@cinematic/domain";
import { parseCanonSectionValue, type ProductionRulesValue } from "@cinematic/domain";
import { describeError } from "../../lib/errors";
import { createCanonEntity, ensureCanonSingletons, getCanonEntity, listCanonEntities, lockCanonSection, unlockCanonSection, upsertCanonSection } from "./api";
import { CanonSectionCard } from "./CanonSectionCard";
import { CanonHistoryDialog } from "./CanonHistoryDialog";

export interface CategoryConfig { type: CanonEntityType; label: string; sections: Array<{ key: string; title: string; kind: "text" | "list" | "rules" | "production" }>; singleton?: boolean; }
const defaults = (kind: CategoryConfig["sections"][number]["kind"]) => kind === "text" ? { text: "" } : kind === "list" ? { tags: [] } : { rules: [] };

export function EntityCategoryEditor({ projectRootPath, config }: { projectRootPath: string; config: CategoryConfig }) {
  const [entities, setEntities] = useState<CanonEntity[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [name, setName] = useState(""); const [error, setError] = useState<string | null>(null);
  async function load() { try { if (config.singleton) { const result = await ensureCanonSingletons(projectRootPath); setEntities([config.type === "production_rules" ? result.productionRules : result.story]); setSelectedId(config.type === "production_rules" ? result.productionRules.id : result.story.id); } else { const result = await listCanonEntities(projectRootPath, config.type); setEntities(result); if (selectedId && !result.some((entity) => entity.id === selectedId)) setSelectedId(null); } setError(null); } catch (caught) { setError(describeError(caught)); } }
  useEffect(() => { void load(); }, [projectRootPath, config.type]);
  async function create(event: React.FormEvent) { event.preventDefault(); try { const entity = await createCanonEntity({ projectRootPath, type: config.type as Exclude<CanonEntityType, "story" | "production_rules">, name }); setName(""); setSelectedId(entity.id); await load(); } catch (caught) { setError(describeError(caught)); } }
  const selected = entities.find((entity) => entity.id === selectedId) ?? null;
  return <section aria-label={config.label} className="canon-content"><header className="canon-panel-header"><div><h2>{config.label}</h2><p>Deterministic structured canon with independent section locks.</p></div></header>{!config.singleton ? <form onSubmit={create} className="canon-create-form"><label>Name<input value={name} onChange={(event) => setName(event.target.value)} required /></label><button type="submit">New {config.label.replace(/s$/, "")}</button></form> : null}{error ? <p role="alert">{error}</p> : null}<div className="canon-entity-layout">{!config.singleton ? <aside><ul className="canon-entity-list">{entities.map((entity) => <li key={entity.id}><button type="button" className={selectedId === entity.id ? "canon-entity-button canon-entity-button--selected" : "canon-entity-button"} onClick={() => setSelectedId(entity.id)}>{entity.name}</button></li>)}</ul></aside> : null}{selected ? <CategoryEditor projectRootPath={projectRootPath} entity={selected} config={config} /> : <p>{config.singleton ? "Loading…" : `Create a ${config.label.toLowerCase().replace(/s$/, "")} to begin.`}</p>}</div></section>;
}

function CategoryEditor({ projectRootPath, entity, config }: { projectRootPath: string; entity: CanonEntity; config: CategoryConfig }) {
  const [detail, setDetail] = useState<CanonEntityDetail | null>(null); const [history, setHistory] = useState<{ id: string; title: string } | null>(null); const [error, setError] = useState<string | null>(null);
  async function load() { try { setDetail(await getCanonEntity(projectRootPath, entity.id)); setError(null); } catch (caught) { setError(describeError(caught)); } }
  useEffect(() => { void load(); }, [projectRootPath, entity.id]);
  const sections = useMemo(() => new Map((detail?.sections ?? []).map((section) => [section.key, section])), [detail]);
  if (!detail) return <div className="canon-editor-pane">{error ? <p role="alert">{error}</p> : <p>Loading…</p>}</div>;
  async function save(key: string, value: unknown) { await upsertCanonSection({ projectRootPath, entityId: entity.id, sectionKey: key, value }); await load(); }
  async function changeLock(section: CanonSection<unknown>, locked: boolean) { await (locked ? lockCanonSection : unlockCanonSection)({ projectRootPath, sectionId: section.id }); await load(); }
  return <div className="canon-editor-pane"><h3>{entity.name}</h3>{error ? <p role="alert">{error}</p> : null}<div className="canon-section-grid">{config.sections.map(({ key, title, kind }) => { const section = sections.get(key) as CanonSection<unknown> | undefined; return <CanonSectionCard key={`${key}-${section?.revision ?? 0}-${section?.status ?? "draft"}`} title={title} section={section ?? null} draftValue={section?.value ?? defaults(kind)} validate={(value) => parseCanonSectionValue(config.type, key, value)} renderEditor={(value, onChange) => <SimpleStructuredEditor kind={kind} value={value} onChange={onChange} />} renderReadOnly={(value) => <SimpleStructuredReadOnly kind={kind} value={value} />} onSave={(value) => save(key, value)} onLock={() => section ? changeLock(section, true) : Promise.resolve()} onUnlock={() => section ? changeLock(section, false) : Promise.resolve()} onHistory={() => section && setHistory({ id: section.id, title })} />; })}</div><CanonHistoryDialog projectRootPath={projectRootPath} sectionId={history?.id ?? null} sectionTitle={history?.title ?? "Section"} onClose={() => setHistory(null)} /></div>;
}

function SimpleStructuredEditor({ kind, value, onChange }: { kind: "text" | "list" | "rules" | "production"; value: unknown; onChange: (value: unknown) => void }) { if (kind === "text") return <textarea value={(value as { text: string }).text} onChange={(event) => onChange({ text: event.target.value })} rows={4} />; if (kind === "production") { const rules = (value as ProductionRulesValue).rules; return <div className="canon-list-editor">{rules.map((rule, index) => <div className="canon-list-row" key={rule.id}><label>Title<input value={rule.title} onChange={(event) => { const next = [...rules]; next[index] = { ...rule, title: event.target.value }; onChange({ rules: next }); }} /></label><label>Body<textarea value={rule.body} onChange={(event) => { const next = [...rules]; next[index] = { ...rule, body: event.target.value }; onChange({ rules: next }); }} /></label><button type="button" className="canon-secondary-button" onClick={() => onChange({ rules: rules.filter((_, rowIndex) => rowIndex !== index) })}>Remove</button></div>)}<button type="button" className="canon-secondary-button" onClick={() => onChange({ rules: [...rules, { id: crypto.randomUUID(), title: "", body: "" }] })}>Add rule</button></div>; } const key = kind === "list" ? "tags" : "rules"; const values = (value as Record<string, string[]>)[key]; return <label>{key}<textarea value={values.join("\n")} onChange={(event) => onChange({ [key]: event.target.value.split("\n") })} rows={4} /></label>; }
function SimpleStructuredReadOnly({ kind, value }: { kind: "text" | "list" | "rules" | "production"; value: unknown }) { if (kind === "text") return <p>{(value as { text: string }).text || "[TBD]"}</p>; if (kind === "production") return <ul>{(value as ProductionRulesValue).rules.map((rule) => <li key={rule.id}><strong>{rule.title}</strong> — {rule.body}</li>)}</ul>; const key = kind === "list" ? "tags" : "rules"; return <ul>{(value as Record<string, string[]>)[key].filter(Boolean).map((item) => <li key={item}>{item}</li>)}</ul>; }

export function ProductionRulesCategory({ projectRootPath }: { projectRootPath: string }) { return <ProductionRulesEditor projectRootPath={projectRootPath} />; }
export function ProductionRulesEditor({ projectRootPath }: { projectRootPath: string }) { return <EntityCategoryEditor projectRootPath={projectRootPath} config={{ type: "production_rules", label: "Production Rules", singleton: true, sections: [{ key: "rules", title: "Production Rules", kind: "production" }] }} />; }
export function rulesValue(value: ProductionRulesValue): ProductionRulesValue { return value; }
