import { useEffect, useState } from "react";
import type { CanonEntity, CanonTbd } from "@cinematic/domain";
import { describeError } from "../../lib/errors";
import { createCanonTbd, listCanonEntities, listCanonTbds, reopenCanonTbd, resolveCanonTbd } from "./api";

export function TbdPanel({ projectRootPath }: { projectRootPath: string }) {
  const [tbds, setTbds] = useState<CanonTbd[]>([]); const [entities, setEntities] = useState<CanonEntity[]>([]); const [topic, setTopic] = useState(""); const [note, setNote] = useState(""); const [protectedTbd, setProtectedTbd] = useState(true); const [entityId, setEntityId] = useState(""); const [sectionKey, setSectionKey] = useState(""); const [resolutions, setResolutions] = useState<Record<string, string>>({}); const [error, setError] = useState<string | null>(null);
  async function load() { try { setTbds(await listCanonTbds(projectRootPath)); setEntities(await listCanonEntities(projectRootPath)); setError(null); } catch (caught) { setError(describeError(caught)); } }
  useEffect(() => { void load(); }, [projectRootPath]);
  async function create(event: React.FormEvent) { event.preventDefault(); try { await createCanonTbd({ projectRootPath, topic, note: note || null, protected: protectedTbd, canonEntityId: entityId || null, sectionKey: sectionKey || null }); setTopic(""); setNote(""); await load(); } catch (caught) { setError(describeError(caught)); } }
  async function resolve(tbd: CanonTbd) { const resolutionText = (resolutions[tbd.id] ?? "").trim(); if (!resolutionText) { setError("Resolution text must not be blank"); return; } try { await resolveCanonTbd({ projectRootPath, tbdId: tbd.id, resolutionText }); setResolutions((current) => ({ ...current, [tbd.id]: "" })); await load(); } catch (caught) { setError(describeError(caught)); } }
  async function reopen(tbd: CanonTbd) { try { await reopenCanonTbd({ projectRootPath, tbdId: tbd.id }); await load(); } catch (caught) { setError(describeError(caught)); } }
  return <section aria-label="TBDs" className="canon-content"><header className="canon-panel-header"><div><h2>Protected TBDs</h2><p>Unknown canon stays unknown until intentionally resolved.</p></div></header><form onSubmit={create} className="canon-create-form"><label>Topic<input value={topic} onChange={(event) => setTopic(event.target.value)} required /></label><label>Note<textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><label>Scope entity<select value={entityId} onChange={(event) => setEntityId(event.target.value)}><option value="">Project-wide</option>{entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</select></label><label>Section key (optional)<input value={sectionKey} onChange={(event) => setSectionKey(event.target.value)} /></label><label className="canon-checkbox"><input type="checkbox" checked={protectedTbd} onChange={(event) => setProtectedTbd(event.target.checked)} /> Protected</label><button type="submit">Add TBD</button></form>{error ? <p role="alert">{error}</p> : null}<ul className="canon-tbd-list">{tbds.map((tbd) => <li key={tbd.id} className="canon-tbd-card"><div><strong>{tbd.topic}</strong>{tbd.protected ? <span className="canon-badge">PROTECTED</span> : null}<span className="canon-badge">{tbd.status.toUpperCase()}</span></div>{tbd.note ? <p>{tbd.note}</p> : null}{tbd.resolutionText ? <p><strong>Resolution:</strong> {tbd.resolutionText}</p> : null}{tbd.status === "open" ? <div className="canon-tbd-action"><input aria-label={`Resolution for ${tbd.topic}`} value={resolutions[tbd.id] ?? ""} onChange={(event) => setResolutions((current) => ({ ...current, [tbd.id]: event.target.value }))} placeholder="Resolution" /><button type="button" onClick={() => void resolve(tbd)}>Resolve</button></div> : <button type="button" onClick={() => void reopen(tbd)}>Reopen</button>}</li>)}</ul></section>;
}
